### ISSUE TITLE
Add posibility to change location of the config file

### ISSUE THREAD

**Issue by markelarizaga** [zeplin/vscode-extension#100]
The extension can automatically generate the config file in the project root, under the `.zeplin` folder. However, some projects could require having the mentioned folder in other location different from the project root. Fore example in a repo that contains several projects and only one is a frontend project, it would make sense to host the config file in the frontend projects root folder.
Unless I have missed it, I don't see in the docs nor in the settings of the extension a way to change the default location.
This causes some features of the extensions not to be available.
I guess that an entry in the extension settings where users can specify the route to the config file would be enough.

**Comment by fonurr** [comment]
Thanks for the suggestion. We decided how to implement this and will start implementing shortly.
