### ISSUE TITLE
Unable to get Zeplin VSCode plugin command to create JSON config file

### ISSUE THREAD

**Issue by deborah-ufw** [zeplin/vscode-extension#103]
Hi everyone, Thank you for this awesome plugin!!

I've installed it and logged into my Zeplin account. My team uses yarn instead of npm, so I've installed the Zeplin plugin with `yarn global add @zeplin/cli-connect-storybook-plugin`.

EDIT: The install actually failed with many complaints in Terminal about Darwin, so with permission of my team I used the recommended npm install. However, though the install seemed to go all right, attempting to `-p @zeplin/cli-connect-react-plugin` resulted in `-bash: zeplin: command not found`.

Several documents refer to a configuration JSON file that should be edited, and it took a while to find out where and how to find or create it. After a lot of circular clicking I finally found information that this plugin could create it for me.

However, the plugin did not prompt to create the file (though the documentation says it will), there is no link in the plugin to create it, and the promised magical command, "Command/Ctrl + Shift + P" from [the only readme that provides information about creating the file](https://github.com/zeplin/connected-components-docs/blob/master/docs/gettingStarted/REACT.md) fails without error.

I see that I can create it manually, but it would be nicer if the plugin worked as intended. Overall, the process of connecting Zeplin to Storybook so far has been painful.

EDIT: Tried to create .zeplin/components.json manually at the root of my repo, but Zeplin did not seem to know about it or recognize that anything had changed. Meanwhile, the plugin does add my Zeplin projects and styleguides, but there is no visibility for where to find the configuration file the plugin is actually using - and Zeplin still does not allow me to connect any components in Zeplin.

**Comment by fonurr** [comment]
I am closing this because it seems resolved in in https://github.com/zeplin/connected-components-docs/issues/24. Please reopen and tell us more if I am wrong. Thanks!
