### ISSUE TITLE
Changing the authentication token

### ISSUE THREAD

**Issue by alextate4** [zeplin/vscode-extension#108]
Good morning!

I recently added this extension but signed in with my personal account when I meant to use my student account. I attempted to uninstall and reinstall, however, the token has not reloaded. Is anybody familiar with how to change over to my student account? 

Thank you.

![zepelin-token](https://user-images.githubusercontent.com/24833973/96880890-51a40480-1443-11eb-9571-b987b88813e5.PNG)

**Comment by fonurr** [comment]
Hi @alextate4,
Please go to https://app.zeplin.io, then logout and login with your desired account. Then go to VS Code to run login command. Let me know if it works

**Comment by alextate4** [comment]
How do I run the login command? I did not see that in the docs.

**Comment by fonurr** [comment]
You can press `cmd/ctrl + shift + p` and type `Login to Zeplin` and run that command.

**Comment by alextate4** [comment]
This works. Thank you!
