### ISSUE TITLE
No app in ms store

### ISSUE THREAD

**Issue by Guyr989** [zeplin/vscode-extension#109]
Installed the extension (windows) and clicked the project than clicked open via the ms store. there is no zeplin app in the store and kept beeing asked if I want to download the app from it. tried reinstalling the extension... didn't help.

![image](https://user-images.githubusercontent.com/21982152/97103234-d4cb9180-16b3-11eb-85d1-010af4ee416d.png)
![image](https://user-images.githubusercontent.com/21982152/97103261-080e2080-16b4-11eb-8757-45191041d149.png)

![image](https://user-images.githubusercontent.com/21982152/97103244-e14fea00-16b3-11eb-9230-ac132fb4e122.png)

**Comment by fonurr** [comment]
@Guyr989 That's is windows' default dialog for not-installed apps. We have no control over it.

You can download windows application [here](https://support.zeplin.io/en/articles/244698-downloading-mac-and-windows-apps).

If don't want to use the windows app, you can still use the web app on https://app.zeplin.io/

Additionally, you can open _Settings_ in VS Code and type "_Zeplin: Preferred Application Type_" and select "_Web_" option. After doing that when you click "_Open in Zeplin_" button (or double click) on the sidebar the web application will open.
