### ISSUE TITLE
Why don't you add parsing function in component.json?

### ISSUE THREAD

**Issue by bugtype** [zeplin/vscode-extension#73]
Thank you for continuing to add good features. I'd like to make a good suggestion.

`component.json` becomes too large if there are many components.

It seems good to add parsing-readable features such as jest and stroybook

```
// jest
  testRegex: ['.*\\.spec\\.(ts|tsx)$'],
// storybook
  stories: ['../src/**/*.stories.tsx'],
```

### For example
.zeplin/ component.json
```
  zeplinComponent: ['../src/**/*.zeplin.json'],
```

components/ListItemText/zeplin.json
```
    {
      "path": "./ListItemText.tsx",
      "zeplinNames": [
        "Lists/Default/Default/Text",
        "Lists/Default/with Secondary/Text",
        "Lists/Default/with Caption/Text"
      ],
      "storybook": {
        "kind": "core/ListItemText",
        "stories": [
          "Lists/Default/Default/Text",
          "Lists/Default/with Secondary/Text",
          "Lists/Default/with Caption/Text"
        ]
      }
    }
```

Is this the right way to suggest it?
Should I post the issue on the `zeplin-cli`, not here?

**Comment by fonurr** [comment]
Hey @bugtype this is a good suggestion that we are also considering. For now we have a live feature I might suggest you to take a look. It is wildcard support for component zeplinNames. For information see [this document](https://github.com/zeplin/connected-components-docs/blob/master/docs/gettingStarted/REACT.md#connect-to-component-from-zeplin). It is not supported by vscode yet, but we are working on it.

**Comment by fonurr** [comment]
https://github.com/zeplin/vscode-extension/pull/92 brings the wildcard support I mentioned in the previous comment. This is issue will be closed when it is merged, however the original suggestion by @bugtype is beyond vscode extension and will be discussed later by the whole connected components team.
