### ISSUE TITLE
Double-clicking an item should open the design in Zeplin

### ISSUE THREAD

**Issue by chaddjohnson** [zeplin/vscode-extension#76]
Thanks for the fantastic plugin!

I would like to suggest that double-clicking a screen/component item should open the item in Zeplin. The Open in Zeplin icon is useful, but my very first impulse definitely was to double-click items. The Open in Zeplin icon on the side isn't obvious at a glance -- especially if the sidebar isn't wide enough and the icon is hidden as it was for me.

**Comment by ddonahoevibrenthealth** [comment]
Agreed, clicked it a ton of times before realizing you have to click that little icon. Almost though "eh, it's a new extension, maybe i'll try it again once it's working"

**Comment by chaddjohnson** [comment]
> Agreed, clicked it a ton of times before realizing you have to click that little icon. Almost thought "eh, it's a new extension, maybe i'll try it again once it's working"

Yep, I almost passed this extension up until I scrolled horizontally and saw the icon. I bet Zeplin will see better usage stats if they add this one feature.

**Comment by fonurr** [comment]
Thanks for the suggestion! We added it and it will live on the next version.
