### ISSUE TITLE
Add (or document) log-out option

### ISSUE THREAD

**Issue by battaglr** [zeplin/vscode-extension#77]
By mistake I logged-in using my personal credentials instead of the ones from my workplace. I'm not finding a way to log-out. Is this a feature that's not documented or that does not exists? Thanks!

**Comment by fonurr** [comment]
Yes, there is logout option. It is just not visible on the sidebar. It is visible in the command panel (cmd/ctrl+shift+p) then search for "Zeplin: Log out from Zeplin" command.

Tip: So you can just run "Zeplin: Login to Zeplin" command to login again. It will override the previous login info.

**Comment by battaglr** [comment]
Awesome, thank you! Feel free to close this if you think is clear enough or keep it open if you're going to add some documentation.

**Comment by fonurr** [comment]
Thanks for the suggestion. We have some ideas on this, but will consider it throughly later. Closing for now.
