### ISSUE TITLE
Can't see existing projects

### ISSUE THREAD

**Issue by suchy** [zeplin/vscode-extension#78]
Hi ;-)

 Maybe I misunderstood intentions... I installed VSC extension, signed in and I can add project but I can't see already existing one (same project I have access in web app).

Thanks for clarification!

**Comment by fonurr** [comment]
I couldn't understand the problem, sorry. Could you describe the steps you followed and where you can't see the project? If a screenshot or gif would be helpful, you can attach one too. Regards

**Comment by suchy** [comment]
Lets try again ;-) On web app I can see my projects:

<img width="404" alt="Zrzut ekranu 2020-05-28 20 11 18" src="https://user-images.githubusercontent.com/255720/83177532-86739000-a11f-11ea-9b9b-b13197c4975a.png">

Can I see same projects in VSC? Just right from my account?

<img width="363" alt="Zrzut ekranu 2020-05-28 20 12 57" src="https://user-images.githubusercontent.com/255720/83177647-bcb10f80-a11f-11ea-9c8a-a7031c98bf5a.png">

**Comment by fonurr** [comment]
The intention of the extension is to provide user a focused experience per project (called workspace in VSCode). So the extension does not show all the projects the user has joined. Instead, the user has to manually add the relevant project by pressing "Add project" or "Add styleguide" buttons. Can you see the workspaces and then the projects/styleguides you are a member of when you press those buttons?

**Comment by suchy** [comment]
Ok found it. I though I need to upload something from my hard drive. Thanks for clarification ;-)
