### ISSUE TITLE
Enhancement - Web View open as a VSCode tab

### ISSUE THREAD

**Issue by ddonahoevibrenthealth** [zeplin/vscode-extension#80]
Having the option to open web view as a new tab in VSCode would be super useful. Right now the integration is pretty well split between two apps, but this would make everything sit inside VSCode.

**Comment by fonurr** [comment]
Thanks for the suggestion, it is a good idea. However, I am closing this because it is already mentioned on https://github.com/zeplin/vscode-extension/issues/79.
