### ISSUE TITLE
Enhancement - Include preview images in the "Screens and Styleguides" area and in the "Pinned" area of the extension

### ISSUE THREAD

**Issue by ddonahoevibrenthealth** [zeplin/vscode-extension#81]
There should be an option to include screen previews in the Tree Browse section of the extension. Otherwise it makes more sense to just use the app/web entirely when there are lots of screens in large projects.

**Comment by fonurr** [comment]
Thanks for the suggestion, unfortunately VS Code sidebar only supports single line texts and small thumbnails. However, there is an open issue suggests showing image in a webview in VS Code. Please see https://github.com/zeplin/vscode-extension/issues/79
